FROM artifact.srdcloud.cn/iaicenter-llm_agent-release-docker-local/llm/centos-tools:7.9.2009

ENV TZ="Asia/Shanghai"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app

